### ISSUE TITLE
Cannot use AnyDiff within strong-named project.

### ISSUE THREAD

**Issue by joshmachol** [replaysMike/AnyDiff#15]
I want to use AnyDiff within a project that is strong-named. When I try to, I get this exception at runtime.

> System.IO.FileLoadException: Could not load file or assembly 'AnyDiff, Version=1.0.83.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

Because AnyDiff is not strong-named, I cannot use it within this project.

See a similar change made for auth0.net at auth0/auth0.net#281 and Microsoft's recommendation for publicly published .NET libraries [here](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md#1-microsoft-strong-names-their-assemblies-should-i).

**Comment by replaysMike** [comment]
Thanks Josh, I will strongly name this library and try to get it merged by
tomorrow.

**Comment by replaysMike** [comment]
it was longer than I expected, but this is now complete as of version 1.0.88

**Comment by joshmachol** [comment]
Thank you for the quick turn around on this. Very appreciated!
