### ISSUE TITLE
Path is missing the array index

### ISSUE THREAD

**Issue by BrightSoul** [replaysMike/AnyDiff#17]
Hello there, I'm comparing these two objects:
```
var obj1 = new Projection
{
    Speakers = new [] { new Speaker { Id = 1, Name = "Fizz" } }
};

var obj2 = new Projection
{
    Speakers = new [] { new Speaker { Id = 1, Name = "Buzz" } }
};

var diffs = AnyDiff.Diff(obj1, obj2);
```
As you can see, The `Name` property of the first `Speaker` in the array has a different value.
The resulting `Difference` object is omitting the `0` index in the path. It's `.Speakers.Name` but it should be `.Speakers[0].Name`.
<img width="247" alt="speakers" src="https://user-images.githubusercontent.com/1888641/140906130-ae5e582a-8a24-4d12-81cb-a2279606e0bd.png">
Without an index in the `Path`, I can't really tell which of the objects in the array changed.

Thanks,
Moreno

**Comment by digitaldirk** [comment]
Hi,

I just started using this library and ran into this issue as well. I saw in this repo's forks, this one: https://github.com/MohammadHadi2031/AnyDiff has implemented a fix for this issue. 

- If @replaysMike likes/approves the relevant changes in https://github.com/MohammadHadi2031/AnyDiff **AND** @MohammadHadi2031 is willing to let us use their commits. Could a PR be made to solve this issue?
- If not can we come up with a new solution together? I would be willing to help/make a PR.

Thank you

**Comment by MohammadHadi2031** [comment]
I will make a PR soon

**Comment by digitaldirk** [comment]
> I will make a PR soon

Thank you!

**Comment by ScottTunstall** [comment]
Still getting this issue - note in the IEnumerable browser on the right hand side how ArrayIndex of 1 is not included in the Path: 

<img width="2509" height="823" alt="Image" src="https://github.com/user-attachments/assets/c44908b6-2818-47cf-9f30-6dcf4f7c12b4" />


I'm using .NET 9 with Blazor and VS 2022
