### ISSUE TITLE
License

### ISSUE THREAD

**Issue by maciusik** [replaysMike/AnyDiff#23]
hi,
What is the license of the library? github shows GPL 3.0 license but nuget package is AGPL 3.0. Which one is correct?

**Comment by 0x326** [comment]
I am curious about this too. @replaysMike Could you clarify?

**Comment by replaysMike** [comment]
AGPL is incorrect. It's supposed to be GPL 3.0 (no disclosing of code required for inclusion in projects).

I'm fixing this now and will push a new version.

**Comment by replaysMike** [comment]
Made a correction, it will now be an MIT license to be less restrictive for commercial use. Deploying new version (1.0.91) now.
